export const performance = [
    {
      year: "2022",
      APlain: "2",
      AMinus : "10",
      BPlus: "40",
      BPlain: "63",
      BMinus: "71",
      CPlus: "50",
      CPlain: "43",
      CMinus: "29",
      DPlus: "5",
      DPlain: "0",
      DMinus: "0",
      Entry: "313",
      MeanScore: "7.81",
      MeanGrade: "B-",
    },
    {
      year: "2021",
      APlain: "2",
      AMinus : "10",
      BPlus: "40",
      BPlain: "63",
      BMinus: "71",
      CPlus: "50",
      CPlain: "43",
      CMinus: "29",
      DPlus: "5",
      DPlain: "0",
      DMinus: "0",
      Entry: "313",
      MeanScore: "7.81",
      MeanGrade: "B-",
    },
    {
      year: "2020",
      APlain: "2",
      AMinus : "10",
      BPlus: "40",
      BPlain: "63",
      BMinus: "71",
      CPlus: "50",
      CPlain: "43",
      CMinus: "29",
      DPlus: "5",
      DPlain: "0",
      DMinus: "0",
      Entry: "313",
      MeanScore: "7.81",
      MeanGrade: "B-",
    },
    {
      year: "2019",
      APlain: "2",
      AMinus : "10",
      BPlus: "40",
      BPlain: "63",
      BMinus: "71",
      CPlus: "50",
      CPlain: "43",
      CMinus: "29",
      DPlus: "5",
      DPlain: "0",
      DMinus: "0",
      Entry: "313",
      MeanScore: "7.81",
      MeanGrade: "B-",
    },
    {
      year: "2018",
      APlain: "2",
      AMinus : "10",
      BPlus: "40",
      BPlain: "63",
      BMinus: "71",
      CPlus: "50",
      CPlain: "43",
      CMinus: "29",
      DPlus: "5",
      DPlain: "0",
      DMinus: "0",
      Entry: "313",
      MeanScore: "7.81",
      MeanGrade: "B-",
    },
    {
      year: "2017",
      APlain: "2",
      AMinus : "10",
      BPlus: "40",
      BPlain: "63",
      BMinus: "71",
      CPlus: "50",
      CPlain: "43",
      CMinus: "29",
      DPlus: "5",
      DPlain: "0",
      DMinus: "0",
      Entry: "313",
      MeanScore: "7.81",
      MeanGrade: "B-",
    },
    {
      year: "2016",
      APlain: "2",
      AMinus : "10",
      BPlus: "40",
      BPlain: "63",
      BMinus: "71",
      CPlus: "50",
      CPlain: "43",
      CMinus: "29",
      DPlus: "5",
      DPlain: "0",
      DMinus: "0",
      Entry: "313",
      MeanScore: "7.81",
      MeanGrade: "B-",
    },
    {
      year: "2015",
      APlain: "2",
      AMinus : "10",
      BPlus: "40",
      BPlain: "63",
      BMinus: "71",
      CPlus: "50",
      CPlain: "43",
      CMinus: "29",
      DPlus: "5",
      DPlain: "0",
      DMinus: "0",
      Entry: "313",
      MeanScore: "7.81",
      MeanGrade: "B-",
    },
    {
      year: "2014",
      APlain: "2",
      AMinus : "10",
      BPlus: "40",
      BPlain: "63",
      BMinus: "71",
      CPlus: "50",
      CPlain: "43",
      CMinus: "29",
      DPlus: "5",
      DPlain: "0",
      DMinus: "0",
      Entry: "313",
      MeanScore: "7.81",
      MeanGrade: "B-",
    },
    {
      year: "2013",
      APlain: "2",
      AMinus : "10",
      BPlus: "40",
      BPlain: "63",
      BMinus: "71",
      CPlus: "50",
      CPlain: "43",
      CMinus: "29",
      DPlus: "5",
      DPlain: "0",
      DMinus: "0",
      Entry: "313",
      MeanScore: "7.81",
      MeanGrade: "B-",
    },
    {
      year: "2012",
      APlain: "2",
      AMinus : "10",
      BPlus: "40",
      BPlain: "63",
      BMinus: "71",
      CPlus: "50",
      CPlain: "43",
      CMinus: "29",
      DPlus: "5",
      DPlain: "0",
      DMinus: "0",
      Entry: "313",
      MeanScore: "7.81",
      MeanGrade: "B-",
    },
  ];